Crie um array NumPy com 10 elementos inteiros aleatórios no intervalo [0, 100] e exiba os valores e o tipo de dado do array.

In [41]:
import numpy as np
elemento = np.random.randint(0, 100, size=10)
print(elemento)
print(elemento.dtype)

[93 37 87  7 58 27 34 32  6 47]
int32


Crie uma matriz 5x5 com valores aletaorios de [0,1) e encontre o valor minimo, maximo e a média da matriz.

In [58]:
import numpy as np
matriz = np.random.rand(5, 5)
print(matriz)
print(f'Minimo: {np.min(matriz)}')
print(f'Máximo: {np.max(matriz)}')
print(f'Média: {np.average(matriz)}')

[[0.098498   0.87082731 0.15222718 0.98434811 0.81868051]
 [0.80254365 0.63502159 0.42991049 0.51922614 0.09833723]
 [0.19611498 0.50566055 0.13782178 0.70730298 0.76823109]
 [0.34089693 0.42877406 0.57610677 0.29952976 0.7988341 ]
 [0.7670926  0.17597486 0.18783164 0.62834377 0.93968844]]
Minimo: 0.09833723125022675
Máximo: 0.9843481098211293
Média: 0.5147129805603765


Crie um array com 10 elementos aleatórios no intervalo [0,1]. Em seguida, crie um novo array com os elementos do primeiro array multiplicados por 10 e convertidos para inteiro.

In [71]:
import numpy as np
elemento1 = np.random.rand(10)
print(elemento1)
elemento2 = (elemento1 * 10).astype(int)
print(elemento2)


[0.26116223 0.36826521 0.98772037 0.12322495 0.02217971 0.8391685
 0.16478365 0.60873593 0.50728172 0.30715065]
[2 3 9 1 0 8 1 6 5 3]


Crie um array de duas dimensões com shape (3, 3) e valores aleatórios inteiros no intervalo [0, 9]. Substitua todos os elementos da segunda linha por -1.

In [79]:
import numpy as np
elemento = np.random.randint(0, 10, (3, 3))
elemento[1, :] = -1
print(elemento)

[[ 5  4  9]
 [-1 -1 -1]
 [ 7  6  0]]
